### ISSUE TITLE
problem with the updated version of MP 

### ISSUE THREAD

**Issue by shravn9** [DPMI/mp#9]
when I tried downloading this new version mp 0.7.12-git,  I am getting the following error : 

nuka@ubuntu:~/Desktop/mp/build$ make
make  all-am
make[1]: Entering directory `/home/nuka/Desktop/mp/build'
  CCLD     mp-smoke
/usr/local/lib/libcap_utils-07.so: undefined reference to `find_tcp_header'
/usr/local/lib/libcap_utils-07.so: undefined reference to `find_udp_header'
/usr/local/lib/libcap_utils-07.so: undefined reference to `filter_match'
collect2: error: ld returned 1 exit status
make[1]: *** [mp-smoke] Error 1
make[1]: Leaving directory `/home/nuka/Desktop/mp/build'
make: *** [all] Error 2

We did not get this error with the previous version of MP

**Comment by ext** [comment]
What version of libcap_utils is installed?

**Comment by shravn9** [comment]
Hej!

 I have installed the latest version of libcap_utils .

caputils-0.7.15

**Comment by patrikarlos** [comment]
hrm; how did you check that? 
My version is a bit dated, and I'm up to 0.7.17 (not pulled the last doc. updates)

**Comment by shravn9** [comment]
I have checked the caputils version in the NEWS file in the libcap_utils
folder.

**Comment by patrikarlos** [comment]
That file has not been touched since 2014... : ) 
Does not help that two repos are involved, both with a News file :)  
Better do do 
pal@Helicon:/tmp/mp$ git log
**commit c4a164a8fa0bafc8be4590dc00f9d1c57c09c17e**
Author: David Sveningsson <ext@sidvind.com>
Date:   Wed Feb 1 19:34:52 2017 +0100

    version bump
....

and note the 'commit' line, as that allows us to track where you really are. 

Btw, I experience the same issue on a brand new libcap 
lt-capshow-0.7.17-git[3a4498c/master]

It cant link... pkgconfig? (think I've been here before)

**Comment by ext** [comment]
I'll take a look.

**Comment by ext** [comment]
I activated Travis CI and it seems to build fine: https://travis-ci.org/DPMI/mp/jobs/205296995

Can you make sure you are using the latest version of libcap_utils? Remove and reinstall if needed.

**Comment by patrikarlos** [comment]
To me it looks like you just build the libcap_utils twice..

**Comment by ext** [comment]
Ouch, your right. It builds from the wrong directory.

**Comment by patrikarlos** [comment]
So; travis replicates the problem ☺

**Comment by ext** [comment]
A small fix has been make, can you try again with the latest?

**Comment by shravn9** [comment]
Yeah thank you. I'll download the updated version and try .

**Comment by shravn9** [comment]
Hej.

I have tried installing the latest version of libcap_utils and even mp but i get this error everytime I enter mp --help

root@ubuntu:/home/nuka/Desktop/mp# mp --help
mp: error while loading shared libraries: libcap_utils-07.so.2: cannot open shared object file: No such file or directory

I have also tried configuring by providing the path

./configure --with-pcap --without-raw PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

--with-dag is not being identified so I have excluded it.

**Comment by ext** [comment]
Is `libcap_utils-07.so.2` present in `/usr/local/lib`? Is ld configured to look in that directory? Check `/etc/ld.so.conf` and `/etc/ld.so.conf.d/*`

**Comment by patrikarlos** [comment]
When you install libcap_utils; make sure you know where it is installed, and that it matches your systems expectation on where to find libaries. Usually; default works fine, and the only thing you need to do is to run 'ldconfig' (as root) so the system becomes aware of the newly installed libraries. 

I'd keep the mp config simple, and run just
./configure 
omitting any options; think that if you have pcap as capture, you need to call the interfaces with a slightly different name cf the raw/dag approach (check code for details).

**Comment by shravn9** [comment]
Hej,

I have tried installing it again, and its working now . Thank you for the support :)
